### ISSUE TITLE
Поправить загрузку car.js

### ISSUE THREAD

**Issue by dimik** [zxqfox/ymaps#1]
Привет.
Пример перестал работать. Car.js у тебя забирается не из gh-pages ветки, а из мастера http://raw.github.com/zxqfox/ymaps/master/car/car.js?_=1422525036361
поменяй на car.js, должно быть ок

**Comment by qfox** [comment]
Спасибо ;-) Поменяю

**Comment by qfox** [comment]
Починил. Заодно вывел стрелочки вместо буковок в simple.

Спасибо еще раз!
