### ISSUE TITLE
Анимация метки (pinMap)

### ISSUE THREAD

**Issue by leon9208** [zxqfox/ymaps#2]
Добрый день, посмотрел оригинальные примеры реализованные с АПИ Яндекс карты 2,0. Есть ли возможность сделать анимацию метки?
Сделать кастомную метку и применить к метке анимацию, например (bounce). Спасибо )

**Comment by qfox** [comment]
Есть. Но трехмерные объекты просто так не покрутишь, если будет плоская картинка аля вид сверху — https://html5book.ru/css3-animation/
