### ISSUE TITLE
Движение по пешеходному маршруту

### ISSUE THREAD

**Issue by Gaiver1987** [zxqfox/ymaps#3]
Приветствую, наткнулся на скрипт движения машинки по маршруту. Есть возможность сделать тоже самое только чтобы маршрут строился пешеходный а не для авто? Так как при указании координат для въезда в ТРЦ машинка петляет по неведомым маршрутам, а переключить на пешеходный не получается.

**Comment by qfox** [comment]
Если API карт позволяет (раньше не умело), то можно, конечно. Нужно только подсунуть другой набор координат. `route.getWayPoints().getPaths().get(0).getSegments()` — вот здесь, видимо, надо посмотреть в каком формате приходит и взять в API координаты для пешеходов.
